# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bOZ4ZXQ3Xy83R_tv5-dKijadKYtCx0nP
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

!apt-get update -qq
!apt-get install fonts-nanum -qq

import matplotlib.font_manager as fm
fm._load_fontmanager(try_read_cache=False)

plt.rc('font', family = 'NanumBarunGothic')
plt.rcParams['axes.unicode_minus'] = False

print("환경 설정 완료")

bike = pd.read_csv("/content/서울특별시 공공자전거 일별 대여건수_25.7-12.csv",encoding='cp949')

bike.head()

bike.columns.tolist()

bike.info()

bike["대여일자"] = pd.to_datetime(bike["대여일자"])

plt.figure(figsize=(10, 5))
plt.plot(bike["대여일자"],bike["대여건수"])
plt.title('날짜별 따릉이 대여건수 변화', fontsize = 16, fontweight = 'bold')
plt.xlabel('날짜', fontsize = 12)
plt.ylabel('대여건수', fontsize = 12)

plt.grid(alpha=0.3)
plt.tight_layout()
plt.show()

plt.figure(figsize=(10, 5))
plt.hist(bike['대여건수'], bins=15, color='coral', edgecolor='black', alpha=0.7)

plt.title('따릉이 일별 대여건수 분포', fontsize = 16, fontweight = 'bold')
plt.xlabel('대여건수', fontsize = 12)
plt.ylabel('빈도', fontsize = 12)

plt.axvline(bike['대여건수'].mean(), color='red', linestyle='--', label=f'평균: {bike['대여건수'].mean():.1f}') # 평균값

plt.legend() # 범례: 의미하는 바를 명시(빨간 점선이 의미하는 바가 무엇인지 명시해 줌.)
plt.grid(True, alpha= 0.3) # 뒤에 배경선

plt.tight_layout()
plt.show()

bike["7일_이동평균"] = bike["대여건수"].rolling(window=7).mean()


plt.figure(figsize=(12, 5))
plt.plot(bike['대여일자'], bike['대여건수'], alpha=0.4, label="일별 대여건수")
plt.plot(bike["대여일자"], bike["7일_이동평균"], linewidth=2, label='7일 이동평균')

plt.title('따릉이 일별 대여건수 및 7일 이동평균', fontsize = 16, fontweight = 'bold')

plt.xlabel('날짜', fontsize = 12)
plt.ylabel('대여건수', fontsize = 12)
plt.legend
plt.grid(True, alpha= 0.3)
plt.tight_layout()

plt.show()

bike['요일'] = bike['대여일자']. dt.day_name()

weekday_mean = bike.groupby('요일')['대여건수'].mean()

order = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
weekday_mean = weekday_mean.reindex(order)


plt.figure(figsize=(10, 5))
bars = plt.bar(weekday_mean.index, weekday_mean.values, color=['red', 'skyblue', 'grey']) # 막대 그래프 함수

plt.title('요일별 평균 따릉이 대여건수', fontsize = 16, fontweight = 'bold')
plt.xlabel('요일', fontsize = 12)
plt.ylabel('평균 대여건수', fontsize = 12)

for bar in bars:
  height = bar.get_height()
  plt.text(bar.get_x() + bar.get_width() / 2., height, f'{int(height)}건',
          ha='center', va='bottom')
# 막대바 위에 정확한 수 기입 하기 위한 수식

plt.tight_layout() # 폭을 맞춰주는 것(레이아웃, 여백조절)
plt.show()

bike["month"] = bike["대여일자"].dt.month

month = bike.groupby('month')['대여건수'].mean().index
bike_mean = bike.groupby('month')['대여건수'].mean().values

plt.figure(figsize=(10, 5))
plt.plot(month, bike_mean, marker= 'o', linewidth = 2, markersize = 8)

plt.title('월별 평균 따릉이 대여건수', fontsize = 16, fontweight = 'bold')

plt.xlabel('월', fontsize = 12)
plt.ylabel('평균 대여건수', fontsize = 12)

plt.grid(True, alpha= 0.3)
plt.tight_layout()

plt.show()

bike["month"] = bike["대여일자"].dt.month

monthly_mean = bike.groupby('month')['대여건수'].mean()

plt.figure(figsize=(10, 5))
bars = plt.bar(monthly_mean.index, monthly_mean.values, color=['skyblue'])

plt.title('월별 평균 따릉이 대여건수', fontsize = 16, fontweight = 'bold')

plt.xlabel('월', fontsize = 12)
plt.ylabel('평균 대여건수', fontsize = 12)

for bar in bars:
  height = bar.get_height()
  plt.text(bar.get_x() + bar.get_width() / 2., height, f'{int(height)}건',
          ha='center', va='bottom')

plt.show()

